#!/bin/sh -xe

cd $(dirname $0)
rm -rf zu-output/*.*
cd zu-output

INPUTS=$(pwd)/../zu-input/*.*
for n in $INPUTS; do
    BASENAME=$(basename $n)
    [ -e $BASENAME ] || mkdir $BASENAME
    (
        cd $BASENAME
        zu $n >1 2>2
    )
done
ls -l *
