#!/bin/zsh -e
source ~/.localrc
OUT=~/.screenrc
rm -f $OUT 2>&1 >/dev/null || true
touch $OUT
[ ! -z "$SCREENCOLOR" ]
[ ! -z "$SCREENESC" ]
cat <<EOT >> $OUT
shell zsh # is there any other?

defflow off # turn off stupid flow-control (also see: stty -ixon in ~/.zshrc)
maptimeout 0 # for getting rid of the delay of irssi's vim_mode.pl

defscrollback 100000 # maybe more?
altscreen on # restore window contents after "vim", etc.
ignorecase on # for searches
multiuser on
defmonitor on
startup_message off # can't live without this one.
defutf8 on

escape ^$SCREENESC$SCREENESC

# this is crufty looking, but it is a huge usability improvement:
hardstatus alwayslastline "%{${SCREENCOLOR}w}$SCREENESC: %-Lw%{= ${SCREENCOLOR}w}%50>%n%f* %t%{-}%+Lw%< %>"

# this is also crufty, but it gives us 256 colors of power.
term screen-256color-bce
attrcolor b ".I"
termcapinfo xterm 'Co#256:AB=\E[48;5;%dm:AF=\E[38;5;%dm'
defbce "on"
EOT
[ ! -z "$SCREENEXTRA" ] && echo $SCREENEXTRA >> $OUT || true
