#!/bin/zsh

# Not needed unless setopt CORRECT_ALL is on.
# for n in mv cp man svn git; do alias $n="nocorrect $n"; done

# Hrm. Not sure how I want conceive to act these days.
# conceive() { command conceive "$@"; rehash }

# Might revive this one day.
#showbanner() { [ -e .banner ] && cat .banner }
#gitcd() {
#    cd $1
#    showbanner
#    git pull
#    git status
#}

# I still kind of like this little feller.
# alias standup='(echo -n "stand-up: "; randlist < ~/.st-haxors) | xclip'

# TODO
# dict() { /usr/bin/dict -dall "$@" | less -F }

# Kinda rking-specific.
alias ,t='tmux-session shell'
