#!/bin/zsh

# TODO: Pull these into their right *-dot places.

cd() {
    builtin cd "$@"
    local lspp=~/.../src/rking-dots/ls--/ls++
    [ -x $lspp ] && $lspp || true
}

alias cdcfg="cd $DOTDOTDOT_ROOT"
alias CDcfg="gitcd $DOTDOTDOT_ROOT && ... install"
alias vv='vim ~/.vimrc'
alias vz='vim ~/.zshrc; exec zsh'c
for n in mv cp man svn git; do alias $n="nocorrect $n"; done
conceive() { command conceive "$@"; rehash }

alias tl='test-less'
alias tlp='test-less --prove'

alias gemdoc='gem server & sleep 4; firefox-bin 0.0.0.0:8808; fg'
alias be='bundle exec'
alias bui='bundle install'

showbanner() { [ -e .banner ] && cat .banner }
gitcd() {
    cd $1
    showbanner
    git pull
    git status
}

emerge() { $EMERGE_MAYBE_SUDO emerge "$@"; rehash }
alias euses='euses --colour'

type hub >&- && alias git=~/local/bin/hub

alias ls='ls --classify --color=auto'
alias ll='ls -l'
alias la='ls -la'

alias standup='(echo -n "stand-up: "; randlist < ~/.st-haxors) | xclip'

dict() { /usr/bin/dict -dall "$@" | less -F }
kiss() { ~/bin/kiss "$@"; rehash }

s50() { convert -sample 50% $1 $1 }
s75() { convert -sample 75% $1 $1 }

if type pinfo >&-; then
    alias info=pinfo
else
    echo "No pinfo. ☹̆"
fi

echo x | (grep x --color >/dev/null 2>&1) && alias grep='grep --color=auto'

alias cj=clipjoin
alias cb=clipbrowse
alias ce=clipedit

source ~/., # run ,h for help

